python_library(
  dependencies=[
    'pants-plugins/upstreamable/3rdparty/py:pants',
    'pants-plugins/upstreamable/3rdparty/py:twitter.common.collections',
    'pants-plugins/upstreamable/subsystems',
    'pants-plugins/upstreamable/targets',
  ]
)
