python_library(
  dependencies=[
    'pants-plugins/upstreamable/3rdparty:pants',
    'pants-plugins/upstreamable/3rdparty:twitter.common.collections',
    'pants-plugins/upstreamable/subsystems',
    'pants-plugins/upstreamable/targets',
  ]
)
